/**
 * GET /.netlify/functions/saas-v2-agent-summary
 *
 * Returns a plain-language explanation of the workspace's current Retell agent
 * prompt, plus a structured capabilities / gaps list and the raw prompt for
 * the "Show raw prompt" toggle on /v2/agent.
 *
 * The plain-language summary is generated by Sonnet (calmer-density narrative
 * tier per the V2 design system). On any LLM failure we degrade gracefully:
 *   - return the raw prompt
 *   - return a deterministic fallback summary built from the prompt's first
 *     200 chars
 * so the page never breaks for the user.
 *
 * Prompt source resolution (matches the V2 design doc):
 *   1. agents.system_prompt (canonical, per 20260507_agents_system_prompt.sql)
 *      — preferred. Filter by agents.user_id = JWT uid, prefer the most-recently
 *      synced row.
 *   2. If no agents row exists, fall back to retell_prompt_versions where
 *      status='live' for the workspace's vertical (best-effort; column shape
 *      varies across deploys).
 *   3. If neither resolves, return a 404-ish 200 with `raw_prompt: ''` and a
 *      "no agent configured yet" summary so the cold-start UI can render.
 *
 * Auth: Bearer JWT only. Workspace is derived server-side from the JWT — never
 *   accepted from the request.
 *
 * Returns:
 *   {
 *     plain_language_summary: string,
 *     capabilities: string[],
 *     gaps: string[],
 *     raw_prompt: string,
 *     prompt_version: number,
 *     agent_id: string | null,
 *     last_synced_at: string | null,
 *     cold_start: boolean,        // true when no agents row exists yet
 *   }
 *
 * Emits: saas_v2_agent_summary_rendered.
 */

import type { Handler } from '@netlify/functions';

import { getServiceSupabase } from './_shared/token-utils';
import { emitAgencyEvent } from './_shared/emit-agency-event';
import { callClaude } from './_shared/agency-agents/run-agent';


import { getV2CorsHeaders, getRequestOrigin } from './_shared/cors-v2';

interface AgentRow {
  id: string;
  name: string | null;
  retell_agent_id: string | null;
  system_prompt: string | null;
  system_prompt_synced_at: string | null;
}

interface WorkspaceRow {
  id: string;
}

interface SummaryLlmOutput {
  plain_language_summary: string;
  capabilities: string[];
  gaps: string[];
  confidence: number;
  reasoning_trace: string[];
  alternatives_rejected: unknown[];
}

const SUMMARY_SCHEMA = {
  type: 'object' as const,
  properties: {
    plain_language_summary: {
      type: 'string',
      description:
        'Plain-English description of what this agent does, in 3-4 sentences. ' +
        'Must cover: (1) what business it represents, (2) what the agent asks callers, ' +
        '(3) when it transfers vs handles solo, (4) one notable behavior or gap. ' +
        'No jargon, no marketing words like "leverage" or "scalable". ' +
        'Address the business owner directly ("Your agent...").',
    },
    capabilities: {
      type: 'array',
      items: { type: 'string' },
      description:
        'Concrete things the agent CAN do, derived from the prompt. ' +
        '4-8 items. Each item is a short verb phrase like "Books appointments via Cal.com" ' +
        'or "Transfers callers asking for refunds to human staff". No fluff.',
    },
    gaps: {
      type: 'array',
      items: { type: 'string' },
      description:
        'Things the agent CANNOT do or appears to miss, based on what the prompt ' +
        'does NOT say. 2-5 items. Frame as "Does not ask for X" or "No instruction ' +
        'for Y". Honest, specific, never speculative.',
    },
  },
  required: ['plain_language_summary', 'capabilities', 'gaps'],
  additionalProperties: false,
};

async function summarizeViaLlm(
  workspaceId: string,
  rawPrompt: string,
): Promise<SummaryLlmOutput | null> {
  try {
    const result = await callClaude<SummaryLlmOutput>({
      agent_name: 'saas-v2.agent-summary',
      client_id: workspaceId,
      tier: 'sonnet',
      system: [
        "You are the V2 dashboard's plain-English narrator for a local-services business owner.",
        'You read a Retell voice-AI agent prompt and translate it into 3-4 sentences a non-technical owner can understand.',
        'STRICT rules:',
        '- Plain prose. No bullets in the summary text.',
        '- Cite specific behaviors from the prompt — never invent capabilities the prompt does not authorize.',
        '- If the prompt has obvious gaps (no callback handling, no insurance answer, no after-hours rule), name them in the gaps array.',
        '- Keep the summary under 70 words.',
        '- Sound like a calm senior consultant, not a salesperson.',
      ].join('\n'),
      user_messages: [
        {
          role: 'user',
          content:
            '# Your task\n' +
            "Read the Retell agent prompt below and explain what it does to the workspace owner. " +
            'Return the structured JSON via the emit_structured_output tool.\n\n' +
            '# Retell agent prompt\n' +
            '```\n' +
            rawPrompt.slice(0, 12000) + // protect cost on very long prompts
            '\n```',
        },
      ],
      output_schema: SUMMARY_SCHEMA,
    });
    return result.output;
  } catch (err) {
    console.warn('[saas-v2-agent-summary] LLM summary failed', err);
    return null;
  }
}

function buildFallbackSummary(rawPrompt: string): {
  summary: string;
  capabilities: string[];
  gaps: string[];
} {
  if (!rawPrompt) {
    return {
      summary:
        'Your agent does not have a prompt configured yet. Once a prompt is saved we can show you what it does in plain English.',
      capabilities: [],
      gaps: ['No prompt configured'],
    };
  }
  const head = rawPrompt.slice(0, 280).replace(/\s+/g, ' ').trim();
  return {
    summary:
      "We could not generate a plain-language summary right now. Here is the start of your agent's prompt: " +
      head +
      (rawPrompt.length > 280 ? '…' : ''),
    capabilities: [],
    gaps: [],
  };
}

export const handler: Handler = async (event) => {
  const v2cors = getV2CorsHeaders(
    getRequestOrigin(event.headers as Record<string, string>),
    { methods: 'GET' },
  );
  const cors = v2cors.headers;

  function jsonResponse(statusCode: number, body: Record<string, unknown>) {

    return { statusCode, headers: cors, body: JSON.stringify(body) };

  }
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: cors, body: '' };
  }
  if (event.httpMethod !== 'GET') {
    return jsonResponse(405, { error: 'Method not allowed' });
  }

  // ── 1. Auth ──────────────────────────────────────────────────────────────
  const authHeader =
    event.headers['authorization'] || event.headers['Authorization'] || '';
  const token = authHeader.replace(/^Bearer\s+/i, '').trim();
  if (!token) return jsonResponse(401, { error: 'Missing bearer token' });

  const supa = getServiceSupabase();
  const { data: userResult, error: authErr } = await supa.auth.getUser(token);
  if (authErr || !userResult?.user) {
    return jsonResponse(401, { error: 'Invalid or expired token' });
  }
  const userId = userResult.user.id;

  // ── 2. Resolve workspace from JWT (NEVER from body) ─────────────────────
  const { data: workspaceRow, error: wsErr } = await supa
    .from('workspaces')
    .select('id')
    .eq('user_id', userId)
    .limit(1)
    .maybeSingle();
  if (wsErr) {
    console.error('[saas-v2-agent-summary] workspace lookup failed', wsErr);
    return jsonResponse(500, { error: 'Workspace lookup failed' });
  }
  if (!workspaceRow) {
    return jsonResponse(404, { error: 'No workspace found for this user' });
  }
  const workspace = workspaceRow as WorkspaceRow;
  let vertical: string | null = null;
  try {
    const { data: profile } = await supa
      .from('business_profiles')
      .select('main_category')
      .eq('user_id', userId)
      .limit(1)
      .maybeSingle();
    vertical =
      typeof profile?.main_category === 'string' && profile.main_category.trim()
        ? profile.main_category.trim()
        : null;
  } catch (err) {
    console.warn('[saas-v2-agent-summary] business profile vertical probe skipped', err);
  }

  // ── 3. Load the canonical agent prompt ──────────────────────────────────
  // Preferred source: agents.system_prompt (per 20260507_agents_system_prompt.sql).
  // We pick the most-recently synced row owned by this user; fall back to the
  // most-recently created row if none are synced yet.
  let agentRow: AgentRow | null = null;
  try {
    const { data, error } = await supa
      .from('agents')
      .select('id, name, retell_agent_id, system_prompt, system_prompt_synced_at')
      .eq('user_id', userId)
      .order('system_prompt_synced_at', { ascending: false, nullsFirst: false })
      .limit(1)
      .maybeSingle();
    if (error) {
      console.warn('[saas-v2-agent-summary] agents lookup soft-failed', error);
    } else if (data) {
      agentRow = data as AgentRow;
    }
  } catch (err) {
    console.warn('[saas-v2-agent-summary] agents lookup threw', err);
  }

  let rawPrompt = (agentRow?.system_prompt || '').trim();
  let promptVersion = 0;

  // ── 4. Fallback to retell_prompt_versions (best-effort) ─────────────────
  // Column shape varies by deploy (the table was created out-of-band — see
  // recon notes). We probe gently and ignore errors.
  if (!rawPrompt && vertical) {
    try {
      const { data: shadowRow } = await supa
        .from('retell_prompt_versions')
        .select('id, prompt_text')
        .eq('vertical', vertical)
        .eq('status', 'live')
        .order('id', { ascending: false })
        .limit(1)
        .maybeSingle();
      if (shadowRow && typeof shadowRow.prompt_text === 'string') {
        rawPrompt = shadowRow.prompt_text.trim();
        promptVersion = typeof shadowRow.id === 'number' ? shadowRow.id : 0;
      }
    } catch (err) {
      console.warn('[saas-v2-agent-summary] retell_prompt_versions probe skipped', err);
    }
  }

  const coldStart = !rawPrompt;

  // ── 5. Summarize via LLM (or fall back) ─────────────────────────────────
  let plainLanguageSummary = '';
  let capabilities: string[] = [];
  let gaps: string[] = [];
  let narrativeConfidence: number | undefined;

  if (rawPrompt) {
    const llm = await summarizeViaLlm(workspace.id, rawPrompt);
    if (llm) {
      plainLanguageSummary = (llm.plain_language_summary || '').trim();
      capabilities = Array.isArray(llm.capabilities) ? llm.capabilities.slice(0, 10) : [];
      gaps = Array.isArray(llm.gaps) ? llm.gaps.slice(0, 8) : [];
      narrativeConfidence =
        typeof llm.confidence === 'number' ? llm.confidence : undefined;
    }
  }

  if (!plainLanguageSummary) {
    const fb = buildFallbackSummary(rawPrompt);
    plainLanguageSummary = fb.summary;
    capabilities = fb.capabilities;
    gaps = fb.gaps;
  }

  // ── 6. Emit telemetry (best-effort, never blocks the response) ──────────
  try {
    await emitAgencyEvent({
      client_id: workspace.id,
      agent_name: 'saas-v2-agent-summary',
      type: 'saas_v2_agent_summary_rendered',
      severity: 'info',
      payload: {
        workspace_id: workspace.id,
        ...(agentRow?.id ? { agent_id: agentRow.id } : {}),
        ...(promptVersion ? { prompt_version: promptVersion } : {}),
        prompt_length: rawPrompt.length,
        capabilities_count: capabilities.length,
        gaps_count: gaps.length,
        ...(narrativeConfidence !== undefined
          ? { narrative_confidence: narrativeConfidence }
          : {}),
      },
      why_explanation:
        'User opened /v2/agent — plain-language summary rendered for current Retell prompt.',
    });
  } catch (emitErr) {
    console.warn('[saas-v2-agent-summary] event emit failed (non-fatal)', emitErr);
  }

  return jsonResponse(200, {
    plain_language_summary: plainLanguageSummary,
    capabilities,
    gaps,
    raw_prompt: rawPrompt,
    prompt_version: promptVersion,
    agent_id: agentRow?.id ?? null,
    last_synced_at: agentRow?.system_prompt_synced_at ?? null,
    cold_start: coldStart,
  });
};
