/**
 * GET /.netlify/functions/saas-v2-call-detail?call_id=<id>
 *
 * V2 call drawer detail endpoint. JWT-scoped to the caller's workspace.
 * Verifies the requested call belongs to the workspace before returning.
 *
 * Returns:
 *   {
 *     call: { id, caller, status, started_at, duration_sec, qa_score?, sideways_flag, sideways_reason? },
 *     transcript: Array<{ role: 'agent'|'user'|'system', content: string, ts?: string }>,
 *     qa_breakdown?: { score: number, rubric_name?: string, criteria: Array<{ name, score, weight?, passed?, notes? }> } | null,
 *     sideways_narrative?: string | null
 *   }
 *
 * The "sideways_narrative" is generated by a Sonnet pass (heavy tier) using
 * the FULL transcript + outcome. It only runs when the row is flagged sideways.
 * Failures fall back to a deterministic explanation — never block the drawer.
 *
 * Emits: saas_v2_call_drawer_opened with { call_id, has_transcript, has_qa_score }.
 */

import type { Handler } from '@netlify/functions';
import { getServiceSupabase } from './_shared/token-utils';
import { chatCompletion } from './_shared/azure-ai';
import { emitAgencyEvent } from './_shared/emit-agency-event';


import { getV2CorsHeaders, getRequestOrigin } from './_shared/cors-v2';
type TranscriptTurn = { role: string; content: string; ts?: string | null };

function parseTranscript(raw: unknown): TranscriptTurn[] {
  if (Array.isArray(raw)) {
    return (raw as Array<Record<string, unknown>>)
      .map((t) => ({
        role: typeof t.role === 'string' ? t.role : 'agent',
        content: typeof t.content === 'string' ? t.content : '',
        ts: (t.ts as string) || (t.timestamp as string) || null,
      }))
      .filter((t) => t.content);
  }
  if (typeof raw === 'string' && raw.trim()) {
    return raw
      .split(/\n+/)
      .map((line) => {
        const m = /^([A-Za-z]+)\s*:\s*(.*)$/.exec(line);
        return m
          ? { role: m[1].toLowerCase(), content: m[2], ts: null }
          : { role: 'agent', content: line, ts: null };
      })
      .filter((t) => t.content);
  }
  return [];
}

function sidewaysCheck(row: {
  call_status?: string | null;
  status?: string | null;
  duration_sec?: number | null;
  qa_score?: number | null;
}): { flag: boolean; reason: string | null } {
  const status = row.call_status || row.status || '';
  const duration = row.duration_sec ?? 0;
  const score = row.qa_score ?? null;
  const reasons: string[] = [];
  if (duration < 30 && status !== 'booked') {
    reasons.push('call ended in under 30 seconds without a booking');
  }
  if (typeof score === 'number' && score < 60) {
    reasons.push(`QA score ${score} below 60`);
  }
  if (reasons.length === 0) return { flag: false, reason: null };
  return { flag: true, reason: reasons.join('; ') };
}

async function generateSidewaysNarrative(
  callMeta: {
    caller: string;
    status: string;
    duration_sec: number;
    qa_score: number | null;
    outcome: string | null;
  },
  transcript: TranscriptTurn[],
): Promise<string | null> {
  const systemPrompt =
    'You are a plain-English call coach for a local-services business owner. ' +
    'You will receive (1) call metadata and (2) the full transcript of a call that went sideways. ' +
    'Write ONE paragraph (3-5 sentences, max 90 words) that explains, in plain English: ' +
    'what the caller actually wanted, the moment things slipped, and the one fix that would have ' +
    'saved this call. No jargon. No hedging. No marketing words like "leverage" or "scalable". ' +
    'Past tense. Address the business owner directly.';

  const userBody = JSON.stringify({
    meta: callMeta,
    transcript: transcript.map((t) => ({ role: t.role, content: t.content })),
  });

  try {
    const text = await chatCompletion(systemPrompt, userBody, {
      tier: 'heavy', // heavy tier is the Sonnet-equivalent slot per project routing
      maxTokens: 360,
    });
    return text.trim() || null;
  } catch (err) {
    console.warn('[saas-v2-call-detail] sideways narrative failed', err);
    return null;
  }
}

export const handler: Handler = async (event) => {
  const v2cors = getV2CorsHeaders(
    getRequestOrigin(event.headers as Record<string, string>),
    { methods: 'GET' },
  );
  const cors = v2cors.headers;
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, cors, body: '' };
  }
  if (event.httpMethod !== 'GET') {
    return { statusCode: 405, cors, body: JSON.stringify({ error: 'Method not allowed' }) };
  }

  // ── Auth ───────────────────────────────────────────────────────────────
  const authHeader = event.cors['authorization'] || event.cors['Authorization'] || '';
  const token = authHeader.replace(/^Bearer\s+/i, '').trim();
  if (!token) {
    return { statusCode: 401, cors, body: JSON.stringify({ error: 'Missing bearer token' }) };
  }

  const supa = getServiceSupabase();
  const { data: userResult, error: authErr } = await supa.auth.getUser(token);
  if (authErr || !userResult?.user) {
    return { statusCode: 401, cors, body: JSON.stringify({ error: 'Invalid token' }) };
  }
  const userId = userResult.user.id;

  // ── Workspace resolution ───────────────────────────────────────────────
  const { data: workspaceRow, error: wsErr } = await supa
    .from('workspaces')
    .select('id, v2_enabled')
    .eq('user_id', userId)
    .maybeSingle();
  if (wsErr) {
    return { statusCode: 500, cors, body: JSON.stringify({ error: 'Workspace lookup failed' }) };
  }
  if (!workspaceRow) {
    return { statusCode: 404, cors, body: JSON.stringify({ error: 'Workspace not found' }) };
  }
  const workspaceId = workspaceRow.id as string;

  // ── Validate input ─────────────────────────────────────────────────────
  const callId = event.queryStringParameters?.call_id?.trim();
  if (!callId) {
    return { statusCode: 400, cors, body: JSON.stringify({ error: 'call_id is required' }) };
  }

  // ── Fetch the call (workspace_id filter is the security boundary) ──────
  const { data: callRow, error: callErr } = await supa
    .from('retell_calls')
    .select('*')
    .eq('workspace_id', workspaceId)
    .eq('id', callId)
    .maybeSingle();

  if (callErr) {
    console.error('[saas-v2-call-detail] call query failed', callErr);
    return { statusCode: 500, cors, body: JSON.stringify({ error: 'Call query failed' }) };
  }
  if (!callRow) {
    // Not found OR belongs to a different workspace — never differentiate.
    return { statusCode: 404, cors, body: JSON.stringify({ error: 'Call not found' }) };
  }

  // ── Normalize the call envelope ────────────────────────────────────────
  type RetellRow = Record<string, unknown>;
  const row = callRow as RetellRow;
  const caller =
    (row.caller as string) ||
    (row.caller_name as string) ||
    (row.from_number as string) ||
    (row.customer_phone as string) ||
    'Unknown';
  const status = (row.call_status as string) || (row.status as string) || 'unknown';
  const startedAt =
    (row.started_at as string) ||
    (row.start_time as string) ||
    (typeof row.start_timestamp === 'number'
      ? new Date(row.start_timestamp as number).toISOString()
      : (row.start_timestamp as string)) ||
    new Date(0).toISOString();
  const durationSec =
    typeof row.duration_sec === 'number'
      ? (row.duration_sec as number)
      : typeof row.duration === 'number'
        ? (row.duration as number)
        : typeof row.duration_ms === 'number'
          ? Math.round((row.duration_ms as number) / 1000)
          : 0;
  const qaScore = typeof row.qa_score === 'number' ? (row.qa_score as number) : null;
  const outcome = (row.outcome as string) || null;

  const transcriptTurns = parseTranscript(
    (row.transcript_object as unknown) ?? (row.transcript as unknown),
  );

  const side = sidewaysCheck({
    call_status: status,
    duration_sec: durationSec,
    qa_score: qaScore,
  });

  // ── QA breakdown (best-effort join to qa_scores) ───────────────────────
  let qaBreakdown:
    | {
        score: number;
        rubric_name?: string;
        criteria: Array<{
          name: string;
          score: number;
          weight?: number;
          passed?: boolean;
          notes?: string;
        }>;
      }
    | null = null;

  try {
    const { data: scoreRow } = await supa
      .from('qa_scores')
      .select('score, rubric_id, criteria_results, notes')
      .eq('call_id', callId)
      .order('created_at', { ascending: false })
      .limit(1)
      .maybeSingle();
    if (scoreRow) {
      let rubricName: string | undefined;
      if (scoreRow.rubric_id) {
        const { data: rubric } = await supa
          .from('qa_rubrics')
          .select('name')
          .eq('id', scoreRow.rubric_id)
          .maybeSingle();
        rubricName = (rubric?.name as string) || undefined;
      }
      const criteria = Array.isArray(scoreRow.criteria_results)
        ? (scoreRow.criteria_results as Array<Record<string, unknown>>).map((c) => ({
            name: (c.name as string) || (c.criterion as string) || 'Criterion',
            score: typeof c.score === 'number' ? (c.score as number) : 0,
            weight: typeof c.weight === 'number' ? (c.weight as number) : undefined,
            passed: typeof c.passed === 'boolean' ? (c.passed as boolean) : undefined,
            notes: (c.notes as string) || undefined,
          }))
        : [];
      qaBreakdown = {
        score: typeof scoreRow.score === 'number' ? (scoreRow.score as number) : (qaScore ?? 0),
        rubric_name: rubricName,
        criteria,
      };
    }
  } catch (err) {
    // qa_scores table may not exist on this deploy — don't fail the drawer.
    console.warn('[saas-v2-call-detail] qa_scores lookup skipped', err);
  }

  // ── Sideways narrative (only when flagged) ─────────────────────────────
  let sidewaysNarrative: string | null = null;
  if (side.flag && transcriptTurns.length > 0) {
    sidewaysNarrative = await generateSidewaysNarrative(
      {
        caller,
        status,
        duration_sec: durationSec,
        qa_score: qaScore,
        outcome,
      },
      transcriptTurns,
    );
  }
  if (side.flag && !sidewaysNarrative) {
    sidewaysNarrative = `This call was flagged because ${side.reason}. Review the transcript above to see where the caller dropped off.`;
  }

  // ── Emit event ─────────────────────────────────────────────────────────
  try {
    await emitAgencyEvent({
      client_id: workspaceId,
      agent_name: 'saas-v2-call-detail',
      type: 'saas_v2_call_drawer_opened',
      severity: 'info',
      payload: {
        workspace_id: workspaceId,
        call_id: callId,
        has_transcript: transcriptTurns.length > 0,
        has_qa_score: qaScore !== null,
      },
      why_explanation: 'User opened the V2 call detail drawer.',
    });
  } catch (err) {
    console.warn('[saas-v2-call-detail] event emit failed (non-fatal)', err);
  }

  return {
    statusCode: 200,
    cors,
    body: JSON.stringify({
      call: {
        id: callId,
        caller,
        status,
        started_at: startedAt,
        duration_sec: durationSec,
        qa_score: qaScore,
        sideways_flag: side.flag,
        sideways_reason: side.reason,
      },
      transcript: transcriptTurns,
      qa_breakdown: qaBreakdown,
      sideways_narrative: sidewaysNarrative,
    }),
  };
};
