/**
 * CallDetailDrawer — opens when a row in CallList is clicked.
 *
 * Layout (top to bottom):
 *   1. Headline + strategist explanation (design principle #4 — narrative
 *      first, numbers second).
 *   2. QAScoreBreakdown
 *   3. TranscriptViewer (with audio player)
 *
 * Loads from /agency-client-call-detail on open. The explanation is
 * server-generated by Sonnet on first open and cached on the artifact —
 * subsequent opens are free.
 */
import React, { useEffect, useState } from 'react';
import { X } from 'lucide-react';

import { authedFetch } from '../../lib/authedFetch';
import QAScoreBreakdown, { DimNote, DimScore } from './QAScoreBreakdown';
import TranscriptViewer from './TranscriptViewer';

interface CallDetailDrawerProps {
  call_id: string | null;
  onClose: () => void;
}

interface CallDetail {
  call: {
    call_id: string;
    duration_sec: number;
    recording_url: string;
    outcome_raw: string | null;
  };
  transcript: string;
  qa: {
    final_score: number | null;
    dim_scores: DimScore[];
    failure_pattern: { slug?: string; one_line_description?: string } | null;
    notable_moments: string[];
    artifact_id: string | null;
  };
  explanation: {
    headline: string;
    why_it_went_this_way: string;
    what_were_doing_about_it: string;
    per_dim_notes: DimNote[];
  } | null;
}

const CallDetailDrawer: React.FC<CallDetailDrawerProps> = ({
  call_id,
  onClose,
}) => {
  const [detail, setDetail] = useState<CallDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!call_id) {
      setDetail(null);
      setError(null);
      return;
    }
    let cancelled = false;
    setLoading(true);
    setError(null);
    setDetail(null);
    (async () => {
      try {
        const res = await authedFetch(
          `/.netlify/functions/agency-client-call-detail?call_id=${encodeURIComponent(call_id)}`,
        );
        if (!res.ok) {
          throw new Error(`HTTP ${res.status}`);
        }
        const json = (await res.json()) as CallDetail;
        if (!cancelled) setDetail(json);
      } catch (err) {
        if (!cancelled) {
          setError(
            'We could not load this call right now. Try again in a moment.',
          );
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [call_id]);

  if (!call_id) return null;

  return (
    <div className="fixed inset-0 z-50 flex" aria-modal="true" role="dialog">
      <div
        className="flex-1 bg-zinc-900/30 backdrop-blur-sm"
        onClick={onClose}
        aria-label="Close drawer"
      />
      <div className="flex h-full w-full max-w-2xl flex-col overflow-hidden border-l border-zinc-200 bg-white shadow-2xl">
        <header className="flex items-start justify-between border-b border-zinc-200 px-6 py-4">
          <div>
            <p className="text-xs uppercase tracking-wider text-zinc-500">
              Call detail
            </p>
            <p className="mt-0.5 font-mono text-[13px] text-zinc-700">
              {call_id}
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-md p-1.5 text-zinc-500 hover:bg-zinc-100 hover:text-zinc-900"
            aria-label="Close"
          >
            <X size={18} />
          </button>
        </header>

        <div className="flex-1 overflow-y-auto px-6 py-5">
          {loading && (
            <div className="space-y-3">
              <div className="h-6 w-2/3 animate-pulse rounded bg-zinc-100" />
              <div className="h-4 w-full animate-pulse rounded bg-zinc-100" />
              <div className="h-4 w-4/5 animate-pulse rounded bg-zinc-100" />
              <div className="mt-6 h-32 animate-pulse rounded bg-zinc-100" />
            </div>
          )}

          {error && !loading && (
            <div className="rounded-md border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
              {error}
            </div>
          )}

          {detail && !loading && (
            <div className="space-y-6">
              {/* Strategist note — the headline + narrative, principle #1 + #4 */}
              {detail.explanation && (
                <section className="space-y-3">
                  <h2 className="text-lg font-semibold leading-tight text-zinc-900">
                    {detail.explanation.headline}
                  </h2>
                  <p className="text-sm leading-relaxed text-zinc-700">
                    {detail.explanation.why_it_went_this_way}
                  </p>
                  {/* Principle #2: every problem ships with the queued fix */}
                  <div className="rounded-md border border-emerald-200 bg-emerald-50/60 px-4 py-3">
                    <p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">
                      What our team is doing about it
                    </p>
                    <p className="mt-1 text-sm leading-relaxed text-emerald-900">
                      {detail.explanation.what_were_doing_about_it}
                    </p>
                  </div>
                </section>
              )}

              {/* Failure pattern badge (if surfaced by qa-auditor) */}
              {detail.qa.failure_pattern?.slug && (
                <section className="rounded-md border border-amber-200 bg-amber-50/60 px-4 py-3">
                  <p className="text-xs font-semibold uppercase tracking-wider text-amber-800">
                    Pattern detected
                  </p>
                  <p className="mt-1 text-sm leading-relaxed text-amber-900">
                    <code className="rounded bg-amber-100 px-1.5 py-0.5 text-[12px] font-mono text-amber-900">
                      {detail.qa.failure_pattern.slug}
                    </code>{' '}
                    — {detail.qa.failure_pattern.one_line_description}
                  </p>
                </section>
              )}

              {/* QA breakdown */}
              <section>
                <QAScoreBreakdown
                  final_score={detail.qa.final_score}
                  dim_scores={detail.qa.dim_scores}
                  per_dim_notes={detail.explanation?.per_dim_notes}
                />
              </section>

              {/* Notable moments (from qa-auditor's notable_moments[]) */}
              {detail.qa.notable_moments.length > 0 && (
                <section>
                  <h3 className="mb-2 text-sm font-semibold uppercase tracking-wider text-zinc-500">
                    Moments worth listening to
                  </h3>
                  <ul className="space-y-1.5">
                    {detail.qa.notable_moments.map((m, i) => (
                      <li
                        key={i}
                        className="border-l-2 border-zinc-200 pl-3 text-sm text-zinc-700"
                      >
                        {m}
                      </li>
                    ))}
                  </ul>
                </section>
              )}

              {/* Transcript + audio */}
              <section>
                <TranscriptViewer
                  transcript={detail.transcript}
                  recording_url={detail.call.recording_url}
                />
              </section>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CallDetailDrawer;
